USE [spotify]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_genre_dim]    Script Date: 15/2/2024 6:50:59 μμ ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_genre_dim] ON [dbo].[genre_dim]
(
	[genre_name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = ON, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

