USE [spotify]
GO

/****** Object:  Table [dbo].[genre_dim]    Script Date: 15/2/2024 6:37:53 μμ ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[genre_dim](
	[genre_id] [int] IDENTITY(1,1) NOT NULL,
	[genre_name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_genre_dim] PRIMARY KEY CLUSTERED 
(
	[genre_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

