USE [spotify]
GO

/****** Object:  Table [dbo].[key_dim]    Script Date: 15/2/2024 6:38:13 μμ ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[key_dim](
	[key_id] [int] IDENTITY(0,1) NOT NULL,
	[key_label] [varchar](2) NOT NULL,
 CONSTRAINT [PK_key_dim] PRIMARY KEY CLUSTERED 
(
	[key_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

